export const company = {
  name: "Wagtech Africa",
  tagline: "THE ORIGINAL BRAND SINCE 1990",
  description:
    "Africa's Trusted Partner for Water Quality, Environmental Monitoring, Hydromet & Laboratory Solutions",
  subDescription:
    "Delivering advanced scientific equipment, monitoring systems, mobile laboratories, technical training and environmental solutions across Africa.",
  address: "Blixen Court, Suite 15 Off Karen Road, P.O Box 2009-00502, Karen, Nairobi",
  phones: ["+254 797178605", "+254 791284345"],
  whatsapp: "+254720763839",
  email: "info@wagtechafrica.com",
  salesEmail: "sales@wagtechprojects.com",
  regions: ["Kenya", "Tanzania", "South Sudan", "Sudan", "Somalia", "Eritrea"],
  social: {
    facebook: "https://www.facebook.com/Wagtech-Projects-342157306135956",
    twitter: "https://twitter.com/WagtechProjects",
    linkedin: "#",
    instagram: "https://www.instagram.com/wagtechprojects",
    youtube: "#",
    whatsapp: "https://wa.me/254720763839",
  },
};

export const stats = [
  { value: "30+", label: "Years Experience" },
  { value: "20+", label: "African Countries Served" },
  { value: "500+", label: "Projects Completed" },
  { value: "1000+", label: "Products Available" },
];

export const waterProducts = [
  {
    id: "aquasafe-wsl20",
    name: "AQUASAFE WSL20",
    category: "Water Safety Laboratory Systems",
    slug: "aquasafe-wsl20",
    image: "/images/products/wsl20.png",
    shortDesc: "Emergency response kit testing pH, free chlorine, total chlorine, turbidity, temperature, and fecal coliforms.",
    description:
      "A compact emergency water safety laboratory in a single buoyant case format allowing easy carriage and fast deployment. The AQUASAFE WSL20 tests pH, free chlorine, total chlorine, turbidity, temperature, and fecal coliforms — everything needed for rapid water safety assessment in the field.",
    features: [
      "Tests pH, free chlorine, total chlorine, turbidity, temperature, fecal coliforms",
      "Single incubator with adjustable temperature settings",
      "Small, single buoyant case format for easy carriage and fast deployment",
      "Variable petri-dish capacity (up to 20) via PetriLok® system",
      "Rechargeable battery pack with integrated docking station",
    ],
    applications: ["Emergency response", "Humanitarian aid", "Field water testing", "Rural water monitoring"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range.pdf" }],
  },
  {
    id: "aquasafe-wsl25plus",
    name: "AQUASAFE WSL25+",
    category: "Water Safety Laboratory Systems",
    slug: "aquasafe-wsl25-plus",
    image: "/images/products/wsl25plus.png",
    shortDesc: "Next-generation portable water safety laboratory with HydroCheck HC1000 and HydroTest HT1000.",
    description:
      "The next generation of portable water safety laboratory. The WSL25+ incorporates a single high-capacity incubator with PetriLok® technology, a lightweight hard anodized aluminum membrane filtration unit, and the HydroCheck HC1000 multi-parameter meter plus HydroTest HT1000 photometer — both IP68 waterproof.",
    features: [
      "Single high-capacity incubator with PetriLok® technology",
      "Lightweight hard anodized aluminum membrane filtration unit",
      "HydroCheck HC1000 multi-parameter meter (IP68 waterproof)",
      "HydroTest HT1000 photometer (IP68 waterproof)",
      "Arsenic testing equipment included",
      "170W rechargeable battery with mains/vehicle charging",
    ],
    applications: ["Field water quality testing", "Municipal water supply monitoring", "Aid sector deployment"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range.pdf" },
    ],
  },
  {
    id: "aquasafe-wsl50-pro",
    name: "AQUASAFE WSL50 PRO",
    category: "Water Safety Laboratory Systems",
    slug: "aquasafe-wsl50-pro",
    image: "/images/products/wsl50pro.png",
    shortDesc: "High-capacity dual incubator water safety lab with PetriLok® technology and wheels for easy transport.",
    description:
      "A high-capacity dual incubator incorporating PetriLok® technology for intensive water safety monitoring operations. The WSL50 PRO features dual independent temperature-controlled chambers with separate timers and a 170W removable rechargeable battery pack, all in a waterproof wheeled case.",
    features: [
      "Dual independent temperature-controlled chambers",
      "Separate timers for each chamber",
      "170W removable rechargeable battery pack",
      "Waterproof case with wheels for portability",
      "PetriLok® high-capacity cartridge technology",
    ],
    applications: ["Large-scale water monitoring", "National water quality programs", "Municipal water utilities"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range.pdf" },
    ],
  },
  {
    id: "aquasafe-msl25-pro",
    name: "AQUASAFE MSL25 PRO",
    category: "Microbiological Safety Laboratories",
    slug: "aquasafe-msl25-pro",
    image: "/images/products/msl25pro.png",
    shortDesc: "Compact microbiological testing solution integrating with existing photometric and electrochemical equipment.",
    description:
      "A compact microbiological testing solution designed to integrate seamlessly with existing photometric and electrochemical equipment. The MSL25 PRO features a single incubator with PetriLok® cartridge technology in a waterproof carry case with docking station.",
    features: [
      "Single incubator with PetriLok® cartridge technology",
      "Integrates with existing photometric/electrochemical equipment",
      "Waterproof carry case with docking station",
      "Compact form for easy field deployment",
    ],
    applications: ["Microbiological water testing", "Laboratory supplementation", "Field microbiology"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range.pdf" }],
  },
  {
    id: "aquasafe-msl50",
    name: "AQUASAFE MSL50",
    category: "Microbiological Safety Laboratories",
    slug: "aquasafe-msl50",
    image: "/images/products/msl50.png",
    shortDesc: "Dual incubator microbiological system with independent temperature controls and 170W battery pack.",
    description:
      "The MSL50 is the perfect companion for professionals with existing analysis equipment who need expanded microbiological capacity. Features dual incubator microbiological system with independent temperature controls per chamber and a 170W rechargeable battery pack.",
    features: [
      "Dual incubator with independent temperature controls per chamber",
      "170W rechargeable battery pack",
      "Perfect companion for professionals with existing analysis equipment",
    ],
    applications: ["Expanded microbiological capacity", "Research institutions", "Water utilities"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range.pdf" },
    ],
  },
  {
    id: "metalyser-hm1000",
    name: "METALYSER® PORTABLE HM1000",
    category: "Heavy Metals Analysis",
    slug: "metalyser-hm1000",
    image: "/images/products/hm1000.png",
    shortDesc: "Lightweight portable system for heavy metals analysis with up to 10 parameters.",
    description:
      "A lightweight portable system for heavy metals analysis. The HM1000 features up to 10 possible parameters in a waterproof hard-shell case. The handheld unit can calculate results from single-point standard addition.",
    features: [
      "Up to 10 possible parameters",
      "Waterproof hard-shell case",
      "Handheld unit with single-point standard addition calculation",
      "Lightweight and portable design",
    ],
    applications: ["Field heavy metals screening", "Water quality assessment", "Environmental monitoring"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf" },
    ],
  },
  {
    id: "metalyser-hm2000",
    name: "METALYSER® DELUXE HM2000",
    category: "Heavy Metals Analysis",
    slug: "metalyser-hm2000",
    image: "/images/products/hm2000.png",
    shortDesc: "Enhanced system combining electrochemical and photometric instruments for comprehensive heavy metal detection.",
    description:
      "An enhanced heavy metals analysis system combining electrochemical and photometric instruments. Detects cadmium, lead, zinc, mercury, arsenic, copper, manganese, aluminum, boron, iron, chromium (VI), and nickel. Dual technologies offer a flexible solution for heavy metal screening.",
    features: [
      "Dual electrochemical and photometric technologies",
      "Detects: Cadmium, Lead, Zinc, Mercury, Arsenic, Copper",
      "Detects: Manganese, Aluminum, Boron, Iron, Chromium (VI), Nickel",
      "Flexible solution for comprehensive heavy metal screening",
    ],
    applications: ["Drinking water quality testing", "Industrial effluent monitoring", "Environmental compliance"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf" }],
  },
  {
    id: "metalyser-hm3000",
    name: "METALYSER® FIELD PRO HM3000",
    category: "Heavy Metals Analysis",
    slug: "metalyser-hm3000",
    image: "/images/products/hm3000.png",
    shortDesc: "Professional portable system with 10-inch waterproof tablet PC and up to 16 parameters.",
    description:
      "A professional portable system with a 10-inch waterproof tablet PC. Features multi-point standard addition analysis capability with up to 16 possible parameters. Field users can detect levels as low as 1ppb with confidence.",
    features: [
      "10-inch waterproof tablet PC",
      "Multi-point standard addition analysis",
      "Up to 16 possible parameters",
      "Detection levels as low as 1ppb",
    ],
    applications: [
      "Professional field testing",
      "Research applications",
      "Regulatory compliance testing",
      "Industrial monitoring",
    ],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf" },
    ],
  },
  {
    id: "metalyser-hm4000",
    name: "METALYSER® HM4000",
    category: "Heavy Metals Analysis",
    slug: "metalyser-hm4000",
    image: "/images/products/hm4000.png",
    shortDesc: "Up to six parameters in dual waterproof cases with separate digestion and analysis equipment.",
    description:
      "An inexpensive yet powerful screening tool for the field. The HM4000 features up to six possible parameters in dual waterproof cases, separating digestion and analysis equipment for safer field operation.",
    features: [
      "Up to 6 possible parameters",
      "Dual waterproof cases",
      "Separated digestion and analysis equipment",
      "Inexpensive yet powerful field screening tool",
    ],
    applications: ["Cost-effective field screening", "Agronomy", "Soil analysis", "Water quality testing"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf" },
    ],
  },
  {
    id: "metalyser-hm5000",
    name: "LABORATORY HM5000",
    category: "Heavy Metals Analysis",
    slug: "metalyser-hm5000",
    image: "/images/products/hm5000.png",
    shortDesc: "Professional benchtop voltammetry research system with full electrochemical parameter control.",
    description:
      "A complete professional laboratory voltammetry research system with full electrochemical parameter control. Features automated sample elevation platform, compact electrochemical cell, and built-in nitrogen purging capability. Suitable for undergraduates, post-graduates, and researchers.",
    features: [
      "Full electrochemical parameter control",
      "Automated sample elevation platform",
      "Compact electrochemical cell with built-in nitrogen purging",
      "No mercury drops required",
      "No costly installation needed",
      "Suitable for academic and research use",
    ],
    applications: ["Academic research", "Post-graduate studies", "Industrial R&D", "Reference laboratory testing"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf" }],
  },
  {
    id: "arsenometer-hmas100",
    name: "ARSENOMETER HMAS100",
    category: "Specialty Analysis",
    slug: "arsenometer-hmas100",
    image: "/images/products/arsenometer.png",
    shortDesc: "Portable arsenic analysis kit detecting levels as low as 1ppb with arsenic speciation capability.",
    description:
      "A portable arsenic analysis kit that detects levels as low as 1ppb. Features speciation between Arsenic (III) and Arsenic (V) within 10 minutes. No mercury-based substances required. Includes 200 test reagent supply.",
    features: [
      "Detection levels as low as 1ppb",
      "Speciation between Arsenic (III) and Arsenic (V) within 10 minutes",
      "No mercury-based substances required",
      "200 test reagent supply included",
    ],
    applications: ["Arsenic contamination screening", "Drinking water safety", "Groundwater monitoring"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/arsenometer.pdf" },
    ],
  },
  {
    id: "maji-lite",
    name: "MAJI-LITE",
    category: "Multi-Parameter Water Quality Meters",
    slug: "maji-lite",
    image: "/images/products/maji-lite.jpg",
    shortDesc: "Rugged pocket-sized aluminum single-parameter meter with 8 interchangeable optical electrodes.",
    description:
      "A rugged and pocket-sized aluminum body single-parameter portable meter. Features eight interchangeable optical electrodes measuring turbidity, chlorophyll, algae, Rhodamine, Fluorescein, CDOM/FDOM, and refined oil.",
    features: [
      "Rugged pocket-sized aluminum body",
      "Eight interchangeable optical electrodes",
      "Measures: turbidity, chlorophyll, algae, Rhodamine, Fluorescein, CDOM/FDOM, refined oil",
      "Single-parameter portable design",
    ],
    applications: ["Field water quality checks", "Environmental surveys", "Water utilities"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf" }],
  },
  {
    id: "maji-1000",
    name: "MAJI-1000",
    category: "Multi-Parameter Water Quality Meters",
    slug: "maji-1000",
    image: "/images/products/maji-1000.png",
    shortDesc: "Compact multi-parameter probe with 10 standard parameters and capacity for up to 12 total.",
    description:
      "A compact multi-parameter probe with 10 standard parameters and capacity for 1 ISE and 1 optical electrode addition for a total of 12 parameters. Complete package supplied.",
    features: [
      "10 standard parameters included",
      "Capacity for 1 ISE and 1 optical electrode addition (12 total)",
      "Compact design for field deployment",
      "Complete package supplied",
    ],
    applications: ["Multi-parameter water testing", "River and lake monitoring", "Field surveys"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf" }],
  },
  {
    id: "maji-3000",
    name: "MAJI-3000",
    category: "Multi-Parameter Water Quality Meters",
    slug: "maji-3000",
    image: "/images/products/maji-3000.jpg",
    shortDesc: "Advanced multi-parameter probe with up to 16 parameters, automated sensor cleaning, portable or long-term.",
    description:
      "A large advanced multi-parameter probe measuring 10 standard parameters plus up to 6 additional electrodes for a total of 16 parameters. Features automated sensor cleaning system and can be used for portable or long-term deployment.",
    features: [
      "10 standard parameters plus up to 6 additional electrodes (16 total)",
      "Automated sensor cleaning system",
      "Portable or long-term deployment capability",
    ],
    applications: ["Long-term water monitoring", "River quality surveys", "Environmental compliance"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf" }],
  },
  {
    id: "maji-sonde",
    name: "MAJI-SONDE",
    category: "Multi-Parameter Water Quality Meters",
    slug: "maji-sonde",
    image: "/images/products/maji-sonde.jpg",
    shortDesc: "All-in-one multi-parameter device with 180-day continuous logging and 150,000 dataset memory.",
    description:
      "An all-in-one multi-parameter device with built-in data logging and internal power. Features automated sensor cleaning system and up to 180 days of continuous logging with 150,000 full dataset internal memory capacity.",
    features: [
      "Built-in data logging and internal power",
      "Automated sensor cleaning system",
      "Up to 180 days of continuous logging",
      "150,000 full dataset internal memory capacity",
      "PC/laptop configuration software included",
    ],
    applications: ["Long-term autonomous monitoring", "River and lake deployment", "Environmental surveys"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf" }],
  },
  {
    id: "maji-stat",
    name: "MAJI-STAT",
    category: "Fixed Site Monitoring Systems",
    slug: "maji-stat",
    image: "/images/products/maji-stat.jpg",
    shortDesc: "Fixed site monitoring system for up to 16 simultaneous parameters with solar power and data telemetry.",
    description:
      "A fixed site monitoring system for up to 16 simultaneous parameters. Features self-cleaning Maji-3000 probe with 10m cable, solar-powered data hub with battery, data telemetry system, and one-year access to online data management hub.",
    features: [
      "Up to 16 simultaneous parameters",
      "Self-cleaning Maji-3000 probe with 10m cable",
      "Solar-powered data hub with battery",
      "Data telemetry system included",
      "One-year access to online data management hub",
    ],
    applications: ["Fixed water quality monitoring stations", "River monitoring networks", "Water utility surveillance"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf" }],
  },
  {
    id: "dewms",
    name: "DATA EARLY WARNING MANAGEMENT SYSTEM (DEWMS)",
    category: "Fixed Site Monitoring Systems",
    slug: "dewms",
    image: "/images/products/dewms.jpg",
    shortDesc: "Cloud-based platform for flood warning and water quality analysis with early warning alerts.",
    description:
      "A cloud-based platform for flood warning and water quality analysis. Features early warning alerts for water level exceedances, visualization of data in charts, maps and graphs, and calibration management.",
    features: [
      "Cloud-based platform",
      "Early warning alerts for water level exceedances",
      "Visualization in charts, maps and graphs",
      "Calibration management features",
      "Flood warning and water quality analysis",
    ],
    applications: ["Flood early warning", "National water monitoring", "Climate resilience programs"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf" }],
  },
];

export const agronomyProducts = [
  {
    id: "agro-met-station-ag31-200",
    name: "AGROMETEOROLOGICAL STATION AG31-200",
    category: "Agronomy Monitoring",
    slug: "agro-met-station-ag31-200",
    image: "/images/products/agro-station.jpg",
    shortDesc: "Monitors plant health conditions with 8 sensors and 8-channel data logger.",
    description:
      "Monitors conditions affecting plant health with 8 sensors measuring wind speed/direction, air temperature, humidity, solar radiation, soil temperature, surface wetness, and rainfall. Features 8-channel data logger with alkaline batteries and optional solar power pack.",
    features: [
      "8 sensors: wind speed/direction, air temp, humidity, solar radiation, soil temp, surface wetness, rainfall",
      "8-channel data logger with alkaline batteries",
      "Optional solar power pack",
      "Includes 2-meter mast and data transfer software",
      "Optional deluxe software for graphics/tables",
      "Auto software monitors up to 25 stations",
    ],
    applications: ["Crop disease management", "Precision agriculture", "Agricultural research", "Irrigation management"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue.pdf" }],
  },
  {
    id: "hydrological-monitoring-ag31-300",
    name: "HYDROLOGICAL MONITORING STATION AG31-300",
    category: "Agronomy Monitoring",
    slug: "hydrological-monitoring-ag31-300",
    image: "/images/products/agro-hydro-station.jpg",
    shortDesc: "Lightweight hydrological data collection station for monitoring local water conditions.",
    description:
      "A lightweight station for hydrological data collection on local water conditions. Features wind speed/direction, rainfall, and water level (0-10m) sensors with a datalogger, 2-meter frame, solar charger, and rechargeable battery. Portable between sites.",
    features: [
      "Sensors: wind speed/direction, rainfall, water level (0-10m)",
      "Datalogger included",
      "2-meter frame with solar charger and rechargeable battery",
      "Portable between sites",
    ],
    applications: ["Watershed management", "Flood monitoring", "Irrigation planning", "Agricultural water management"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue.pdf" }],
  },
  {
    id: "soil-conditions-ag31-500",
    name: "SOIL CONDITIONS MONITORING SYSTEM AG31-500",
    category: "Agronomy Monitoring",
    slug: "soil-conditions-ag31-500",
    image: "/images/products/agro-soil.jpg",
    shortDesc: "9-channel system measuring soil temperature, water potential, and moisture.",
    description:
      "A 9-channel system measuring soil temperature, water potential, and moisture. Includes 1 soil temperature sensor, 3 tensiometers at 60cm depth, and 3 gypsum block sensors, all with 3-meter cables.",
    features: [
      "9-channel measurement system",
      "1 soil temperature sensor (3m cable)",
      "3 tensiometers at 60cm depth (3m cables)",
      "3 gypsum block sensors (3m cables)",
    ],
    applications: ["Soil moisture management", "Irrigation scheduling", "Drought research", "Crop yield optimization"],
    resources: [{ type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue.pdf" }],
  },
  {
    id: "metalyser-hm4000-agro",
    name: "METALYSER® HM4000 (Agronomy)",
    category: "Soil Analysis",
    slug: "metalyser-hm4000-agro",
    image: "/images/products/hm4000.png",
    shortDesc: "Lightweight portable heavy metals analysis system for soil and agricultural applications.",
    description:
      "A lightweight portable heavy metals analysis system with accessories for up to six parameters in dual waterproof cases. Designed for agronomy use, separating digestion from analysis equipment for safe field screening.",
    features: [
      "Up to 6 parameters",
      "Dual waterproof cases",
      "Intelligent handheld unit with single-point standard addition",
      "Inexpensive field screening tool",
    ],
    applications: ["Soil contamination screening", "Agricultural land assessment", "Fertilizer quality testing"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf" },
    ],
  },
];

export const hydrometProducts = [
  {
    id: "tm50",
    name: "METEOROLOGICAL STATION TM50",
    category: "Automatic Weather Stations",
    slug: "tm50",
    image: "/images/products/tm50.jpg",
    shortDesc: "Compact, low-cost AWS suited for local businesses, institutions or individuals. 7 parameters.",
    description:
      "A compact, low-cost Automatic Weather Station (AWS) suited to local businesses, institutions or individuals. Features 2m mast with 5 sensors measuring 7 meteorological parameters.",
    specs: {
      "Mast Height": "2m",
      "Number of Sensors": "5",
      "Parameters Measured": "7",
    },
    features: [
      "Air temperature", "Barometric pressure", "Rainfall intensity",
      "Relative humidity", "Solar radiation", "Wind direction", "Wind speed",
    ],
    applications: ["Local business weather monitoring", "School weather stations", "Small-scale agriculture"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf" },
      { type: "Catalogue", label: "Hydromet Catalogue", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-catalogue.pdf" },
    ],
  },
  {
    id: "tm100",
    name: "METEOROLOGICAL STATION TM100",
    category: "Automatic Weather Stations",
    slug: "tm100",
    image: "/images/products/tm100.jpg",
    shortDesc: "Premium, full-scale, WMO compliant AWS ideal for national meteorological networks. Very low maintenance.",
    description:
      "A premium, full-scale, WMO compliant AWS ideal for building national meteorological network capacity. Very low maintenance due to the absence of moving parts. 10m mast with 5 sensors measuring 7 parameters.",
    specs: {
      "Mast Height": "10m",
      "Number of Sensors": "5",
      "Parameters Measured": "7",
      "Compliance": "WMO",
    },
    features: [
      "Air temperature", "Barometric pressure", "Rainfall intensity",
      "Relative humidity", "Solar radiation", "Wind direction", "Wind speed",
      "Very low maintenance — no moving parts",
    ],
    applications: ["National meteorological networks", "Government weather agencies", "Climate research"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf" },
      { type: "Catalogue", label: "Hydromet Catalogue", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-catalogue.pdf" },
    ],
  },
  {
    id: "tm50-agro",
    name: "AGROMETEOROLOGICAL STATION TM50 AGRO",
    category: "Agrometeorological Stations",
    slug: "tm50-agro",
    image: "/images/products/tm50-agro.jpg",
    shortDesc: "Compact affordable agronomical AWS building on TM50 with additional soil and leaf sensors. 10 parameters.",
    description:
      "A compact, affordable agronomical system building on the TM50 base station with additional soil and leaf sensors for crop monitoring. Features 2m mast with 7 sensors measuring 10 parameters.",
    specs: {
      "Mast Height": "2m",
      "Number of Sensors": "7",
      "Parameters Measured": "10",
    },
    features: [
      "All TM50 parameters plus:",
      "Leaf wetness", "Soil moisture", "Soil temperature",
    ],
    applications: ["Precision agriculture", "Crop disease monitoring", "Irrigation management"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf" },
      { type: "Catalogue", label: "Agronomy Catalogue", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue.pdf" },
    ],
  },
  {
    id: "tm100-agro",
    name: "AGROMETEOROLOGICAL STATION TM100 AGRO",
    category: "Agrometeorological Stations",
    slug: "tm100-agro",
    image: "/images/products/tm100-agro.jpg",
    shortDesc: "Premium WMO compliant agronomical AWS suited for government agencies. 10 parameters.",
    description:
      "A premium, WMO compliant agronomical AWS suited for government agencies and large-scale agricultural monitoring programs. Features 10m mast with 7 sensors measuring 10 parameters.",
    specs: {
      "Mast Height": "10m",
      "Number of Sensors": "7",
      "Parameters Measured": "10",
      "Compliance": "WMO",
    },
    features: [
      "All TM100 parameters plus:",
      "Leaf wetness", "Soil moisture", "Soil temperature",
    ],
    applications: ["Government agricultural programs", "National agronomy networks", "Climate change adaptation"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf" },
      { type: "Catalogue", label: "Agronomy Catalogue", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue.pdf" },
    ],
  },
  {
    id: "tm50-hydro",
    name: "HYDROMETEOROLOGICAL STATION TM50 HYDRO",
    category: "Hydrometeorological Stations",
    slug: "tm50-hydro",
    image: "/images/products/tm50-hydro.jpg",
    shortDesc: "Compact low-cost hydrological AWS — perfect for community flood early warning and reservoir monitoring.",
    description:
      "A compact, low-cost hydrological AWS perfect for small-scale community-based projects, such as flood early warning or reservoir monitoring. Features 2m mast with 6 sensors measuring 9 parameters including water temperature and water level.",
    specs: {
      "Mast Height": "2m",
      "Number of Sensors": "6",
      "Parameters Measured": "9",
    },
    features: [
      "All TM50 parameters plus:",
      "Water temperature", "Water level",
      "Perfect for flood early warning systems",
    ],
    applications: ["Community flood warning", "Reservoir monitoring", "Small watershed management"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf" },
      { type: "Catalogue", label: "Hydromet Catalogue", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-catalogue.pdf" },
    ],
  },
  {
    id: "tm100-hydro",
    name: "HYDROMETEOROLOGICAL STATION TM100 HYDRO",
    category: "Hydrometeorological Stations",
    slug: "tm100-hydro",
    image: "/images/products/tm100-hydro.jpg",
    shortDesc: "Premium WMO compliant hydrometeorological AWS for government water monitoring agencies. 9 parameters.",
    description:
      "A premium, WMO compliant hydrometeorological AWS for government water monitoring agencies. Features 10m mast with 6 sensors measuring 9 parameters.",
    specs: {
      "Mast Height": "10m",
      "Number of Sensors": "6",
      "Parameters Measured": "9",
      "Compliance": "WMO",
    },
    features: [
      "All TM100 parameters plus:",
      "Water temperature", "Water level",
      "WMO compliant for national networks",
    ],
    applications: ["National hydrological networks", "Government water management", "River basin monitoring"],
    resources: [
      { type: "Brochure", label: "Download Brochure", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf" },
      { type: "Catalogue", label: "Hydromet Catalogue", url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-catalogue.pdf" },
    ],
  },
];

export const solutions = [
  {
    id: "water-quality",
    title: "Water Quality",
    slug: "water-quality",
    shortDesc: "Portable and fixed water testing systems for safe drinking water monitoring across Africa.",
    description:
      "Comprehensive water quality testing solutions from portable field kits to fixed monitoring stations. Covering microbiological, physicochemical, and heavy metals analysis.",
    productCount: 17,
    image: "/images/products/wsl50pro.png",
  },
  {
    id: "agronomy",
    title: "Agronomy",
    slug: "agronomy",
    shortDesc: "Soil and crop monitoring systems for precision agriculture and food security programs.",
    description:
      "Advanced agrometeorological and soil monitoring systems supporting precision agriculture, crop disease management, and food security across Africa.",
    productCount: 4,
    image: "/images/products/agro-station.jpg",
  },
  {
    id: "hydromet",
    title: "Hydromet & Weather",
    slug: "hydromet",
    shortDesc: "WMO-compliant automatic weather stations for national meteorological networks and flood warning.",
    description:
      "Full range of hydrometeorological stations from compact community-level systems to premium WMO-compliant networks for national meteorological agencies.",
    productCount: 6,
    image: "/images/products/tm100.jpg",
  },
  {
    id: "environmental",
    title: "Environmental Monitoring",
    slug: "environmental",
    shortDesc: "Environmental monitoring systems for air, soil, and water quality surveillance.",
    description:
      "Comprehensive environmental monitoring solutions for air quality, soil contamination, and water surveillance programs.",
    productCount: 8,
    image: "/images/products/dewms.jpg",
  },
  {
    id: "mobile-laboratories",
    title: "Mobile Laboratories",
    slug: "mobile-laboratories",
    shortDesc: "Fully equipped mobile lab units deployable to any location for field-based scientific analysis.",
    description:
      "Self-contained mobile laboratory systems designed for deployment in remote and challenging environments across Africa.",
    productCount: 5,
    image: "/images/products/mobile-van-lab.jpg",
  },
  {
    id: "trace2o",
    title: "Trace2O",
    slug: "trace2o",
    shortDesc: "Sister company offering a global range of innovative analytical and monitoring instruments.",
    description:
      "Trace2O is our sister company — a global network of research, development, manufacturing and distribution centres providing cutting-edge analytical instruments.",
    productCount: 10,
    image: "/images/products/hm5000.png",
  },
  {
    id: "laboratory-equipment",
    title: "Laboratory Equipment",
    slug: "laboratory-equipment",
    shortDesc: "Complete laboratory equipment and scientific instrumentation for research and testing institutions.",
    description:
      "Full range of laboratory equipment for water, soil, and environmental analysis in both field and benchtop formats.",
    productCount: 12,
    image: "/images/products/arsenometer.png",
  },
  {
    id: "water-purification",
    title: "Water Purification",
    slug: "water-purification",
    shortDesc: "Water purification and sanitisation systems for safe water access in communities and institutions.",
    description:
      "Advanced water purification and sanitisation systems for humanitarian aid, community water supply, and institutional use.",
    productCount: 6,
    image: "/images/products/aquatabs.png",
  },
];

export const industries = [
  {
    id: "water-utilities",
    title: "Water Utilities",
    description: "Water quality monitoring solutions for municipal water supply authorities and utilities.",
    icon: "utilities",
    challenge: "Ensuring compliance with WHO and national water quality standards across distribution networks.",
    solutions: ["AQUASAFE WSL series", "MAJI-STAT monitoring stations", "METALYSER® systems"],
    products: ["aquasafe-wsl50-pro", "maji-stat", "metalyser-hm2000"],
  },
  {
    id: "humanitarian-aid",
    title: "Humanitarian Aid",
    description: "Emergency response water safety labs and field testing kits for NGOs and aid organizations.",
    icon: "globe",
    challenge: "Rapidly assessing and ensuring safe water supply in emergency and crisis situations.",
    solutions: ["AQUASAFE WSL20 emergency lab", "Leadometer & Arsenometer kits", "Mobile Laboratories"],
    products: ["aquasafe-wsl20", "arsenometer-hmas100", "mobile-box-lab"],
  },
  {
    id: "agriculture",
    title: "Agriculture",
    description: "Soil, weather, and water monitoring systems for commercial and smallholder farming.",
    icon: "leaf",
    challenge: "Optimizing crop yields through precise environmental and soil condition data.",
    solutions: ["Agrometeorological stations", "Soil monitoring systems", "METALYSER® HM4000"],
    products: ["agro-met-station-ag31-200", "soil-conditions-ag31-500", "metalyser-hm4000-agro"],
  },
  {
    id: "government",
    title: "Government & Regulators",
    description: "National-scale monitoring networks and compliance testing equipment for regulatory bodies.",
    icon: "shield",
    challenge: "Building and operating national monitoring networks that meet international compliance standards.",
    solutions: ["TM100 WMO-compliant stations", "DEWMS cloud platform", "MAJI-STAT network"],
    products: ["tm100", "dewms", "maji-stat"],
  },
  {
    id: "research",
    title: "Research & Academia",
    description: "Scientific instrumentation and laboratory systems for universities and research institutions.",
    icon: "flask",
    challenge: "Accessing high-quality analytical instruments at affordable prices for research programs.",
    solutions: ["Laboratory HM5000", "MAJI-SONDE probes", "Agronomy monitoring systems"],
    products: ["metalyser-hm5000", "maji-sonde", "agro-met-station-ag31-200"],
  },
  {
    id: "mining",
    title: "Mining & Industry",
    description: "Heavy metals analysis and environmental monitoring for mining operations and industrial sites.",
    icon: "settings",
    challenge: "Monitoring and controlling heavy metals contamination in water and soil around industrial sites.",
    solutions: ["METALYSER® range", "Environmental monitoring packages", "Laboratory HM5000"],
    products: ["metalyser-hm3000", "metalyser-hm5000", "arsenometer-hmas100"],
  },
  {
    id: "health",
    title: "Public Health",
    description: "Water safety and microbiological testing equipment for public health agencies and hospitals.",
    icon: "check",
    challenge: "Monitoring water safety at the last mile — from treatment plant to point of use.",
    solutions: ["AQUASAFE MSL series", "Aquatabs purification", "Maji monitoring systems"],
    products: ["aquasafe-msl25-pro", "aquasafe-msl50", "dewms"],
  },
  {
    id: "climate",
    title: "Climate & Meteorology",
    description: "WMO-compliant weather stations and climate monitoring systems for meteorological agencies.",
    icon: "sun",
    challenge: "Establishing reliable, low-maintenance climate data networks across diverse African terrain.",
    solutions: ["TM100 & TM50 stations", "Hydrometeorological stations", "DEWMS data platform"],
    products: ["tm100", "tm100-hydro", "dewms"],
  },
];

export const projects = [
  {
    id: "nigeria-nimet",
    country: "Nigeria",
    flag: "🇳🇬",
    title: "Strategic Rainfall Prediction Conference",
    description:
      "Wagtech Projects delivered a presentation on advanced weather monitoring at Nigeria's Strategic Rainfall Prediction conference organized by NIMET.",
    equipment: "TM100 Meteorological Stations",
    industry: "Meteorology",
    client: "NIMET (Nigerian Meteorological Agency)",
    outcome: "Enhanced national rainfall prediction capabilities",
  },
  {
    id: "malawi-weather",
    country: "Malawi",
    flag: "🇲🇼",
    title: "National Weather Station Network",
    description:
      "Weather stations installed across Malawi in collaboration with the Department of Climate Change and Meteorological Services (DCCMS).",
    equipment: "TM100, TM50 Meteorological Stations",
    industry: "Climate & Meteorology",
    client: "DCCMS — Department of Climate Change and Meteorological Services",
    outcome: "40+ weather stations installed across the country",
  },
  {
    id: "malawi-sea-buoy",
    country: "Malawi",
    flag: "🇲🇼",
    title: "Lake Malawi Sea Buoy Deployment",
    description:
      "Sea buoy deployment initiative with Malawi's Department of Climate Change and Meteorological Services for lake water monitoring.",
    equipment: "Aquatic monitoring buoys, water quality sensors",
    industry: "Environmental Monitoring",
    client: "DCCMS — Department of Climate Change and Meteorological Services",
    outcome: "Real-time lake monitoring data for climate research",
  },
  {
    id: "east-africa-water",
    country: "East Africa",
    flag: "🌍",
    title: "Regional Water Quality Monitoring Program",
    description:
      "Supply and installation of portable water safety laboratories and heavy metals analysis systems across East African water utilities.",
    equipment: "AQUASAFE WSL series, METALYSER® systems",
    industry: "Water & Sanitation",
    client: "Multiple water utilities and NGOs",
    outcome: "Improved safe water access for millions across the region",
  },
];

export const news = [
  {
    id: "whatever-the-weather",
    title: "Whatever The Weather",
    date: "January 7, 2022",
    slug: "whatever-the-weather",
    excerpt:
      "Wagtech Projects feature in Meteorological Technology's latest online issue. Read all about how Wagtech Projects have installed 40 weather stations across Malawi.",
    category: "News",
    image: "/images/gallery/20.jpg",
  },
  {
    id: "strategic-rainfall",
    title: "Wagtech Projects Shine at Strategic Rainfall Prediction Conference",
    date: "January 7, 2022",
    slug: "strategic-rainfall-prediction",
    excerpt:
      "Zak Karim from Wagtech Projects delivered a presentation at Nigeria's Strategic Rainfall Prediction conference organized by NIMET.",
    category: "Events",
    image: "/images/gallery/21.jpg",
  },
  {
    id: "weather-stations-nigeria",
    title: "Weather Stations Make a Mark in Nigeria",
    date: "January 7, 2022",
    slug: "weather-stations-nigeria",
    excerpt:
      "Wagtech Projects collaborated with Malawi's government through the Department of Climate Change and Meteorological Services (DCCMS).",
    category: "Projects",
    image: "/images/gallery/22.jpg",
  },
  {
    id: "sea-buoy-malawi",
    title: "Sea Buoy Success in Malawi",
    date: "January 7, 2022",
    slug: "sea-buoy-malawi",
    excerpt:
      "Another Wagtech Projects initiative with Malawi's Department of Climate Change and Meteorological Services (DCCMS) — lake monitoring buoy deployment.",
    category: "Projects",
    image: "/images/gallery/23.jpg",
  },
];

export const events = [
  {
    id: "met-tech-expo",
    title: "Meteorological Technology World Expo",
    date: "September 22",
    location: "Place de la Porte de Versailles",
    description: "Join Wagtech Africa at the premier global event for meteorological technology professionals.",
    registrationUrl: "#",
  },
  {
    id: "wedc-conference",
    title: "WEDC International Conference",
    date: "September 7",
    location: "Loughborough University",
    description:
      "The Water, Engineering and Development Centre (WEDC) international conference on water and sanitation for developing countries.",
    registrationUrl: "#",
  },
];

export const downloads = [
  // ─── English Brochures ────────────────────────────────────────────────────────
  {
    id: "aquasafe-range-en",
    title: "AQUASAFE Range Brochure",
    category: "Water Safety Labs",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "6 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range.pdf",
    thumbnail: "/brochures/thumbnails/aquasafe-range.png",
    description: "Portable Water Safety Laboratories — complete range overview",
  },
  {
    id: "metalyser-range-en",
    title: "METALYSER® Range Brochure",
    category: "Heavy Metals Analysis",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "3 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range.pdf",
    thumbnail: "/brochures/thumbnails/metalyser-range.png",
    description: "Portable Trace Heavy Metal Analysers — full product range",
  },
  {
    id: "maji-systems-en",
    title: "MAJI Systems Brochure",
    category: "Water Quality Meters",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "8 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems.pdf",
    thumbnail: "/brochures/thumbnails/maji-systems.png",
    description: "Water Quality & Level Monitoring — Maji product range",
  },
  {
    id: "arsenometer-en",
    title: "ARSENOMETER HMAS100 Brochure",
    category: "Heavy Metals Analysis",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "2 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/arsenometer.pdf",
    thumbnail: "/brochures/thumbnails/arsenometer.png",
    description: "Portable Arsenic Testing Kit",
  },
  {
    id: "leadometer-en",
    title: "LEADOMETER Brochure",
    category: "Heavy Metals Analysis",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "2 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/leadometer.pdf",
    thumbnail: "/brochures/thumbnails/leadometer.png",
    description: "Portable Lead Testing Kit",
  },
  {
    id: "hydromet-brochure-en",
    title: "Hydromet Brochure",
    category: "Hydromet",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "4 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-brochure.pdf",
    thumbnail: "/brochures/thumbnails/hydromet-brochure.png",
    description: "Meteorological Applications — overview brochure",
  },
  {
    id: "tracemet-stations-en",
    title: "TraceMet Weather Stations Brochure",
    category: "Hydromet",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "10 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/tracemet-weather-stations.pdf",
    thumbnail: "/brochures/thumbnails/tracemet-weather-stations.png",
    description: "Automatic Weather Stations — TM50, TM100, AGRO & HYDRO variants",
  },
  {
    id: "hydromet-catalogue-en",
    title: "Hydromet Catalogue",
    category: "Hydromet",
    type: "Catalogue",
    language: "English",
    format: "PDF",
    size: "4 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-catalogue.pdf",
    thumbnail: "/brochures/thumbnails/hydromet-catalogue.png",
    description: "Integrated Field Systems for Weather and Climate Monitoring",
  },
  {
    id: "agronomy-catalogue-en",
    title: "Agronomy Catalogue",
    category: "Agronomy",
    type: "Catalogue",
    language: "English",
    format: "PDF",
    size: "11 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue.pdf",
    thumbnail: "/brochures/thumbnails/agronomy-catalogue.png",
    description: "Instruments for Agricultural Sciences",
  },
  {
    id: "mobile-labs-en",
    title: "Mobile Laboratories Brochure",
    category: "Mobile Laboratories",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "10 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/mobile-laboratories.pdf",
    thumbnail: "/brochures/thumbnails/mobile-laboratories.png",
    description: "Our Full Range of Mobile Laboratory Systems",
  },
  {
    id: "aquatabs-en",
    title: "Aquatabs Brochure",
    category: "Water Purification",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "4 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquatabs.pdf",
    thumbnail: "/brochures/thumbnails/aquatabs.png",
    description: "Water Purification and Disinfectant Solutions",
  },
  {
    id: "asms-brochure-en",
    title: "ASMS Software Brochure",
    category: "Data Management",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "5 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/asms-software.pdf",
    thumbnail: "/brochures/thumbnails/asms-software.png",
    description: "The AquaSafe Management System (ASMS) — cloud-based dashboard",
  },
  {
    id: "asms-cloud-en",
    title: "ASMS Cloud Dashboard Brochure",
    category: "Data Management",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "5 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/asms-cloud-dashboard.pdf",
    thumbnail: "/brochures/thumbnails/asms-cloud-dashboard.png",
    description: "Cloud-Based Dashboard for AquaSafe Management System",
  },
  {
    id: "environmental-en",
    title: "Environmental Monitoring Brochure",
    category: "Environmental",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "5 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/environmental-brochure.pdf",
    thumbnail: "/brochures/thumbnails/environmental-brochure.png",
    description: "Environmental Monitoring Solutions",
  },
  {
    id: "maji-brochure-en",
    title: "Maji Brochure",
    category: "Water Quality Meters",
    type: "Brochure",
    language: "English",
    format: "PDF",
    size: "2 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-brochure.pdf",
    thumbnail: "/brochures/thumbnails/maji-brochure.png",
    description: "Water Quality & Level Monitoring Systems",
  },
  {
    id: "water-catalogue-en",
    title: "Water Quality Catalogue",
    category: "Water Safety Labs",
    type: "Catalogue",
    language: "English",
    format: "PDF",
    size: "112 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/water-brochure.pdf",
    thumbnail: "/brochures/thumbnails/water-brochure.png",
    description: "Full Water Quality Equipment Catalogue",
  },
  // ─── French Brochures ─────────────────────────────────────────────────────────
  {
    id: "aquasafe-range-fr",
    title: "AQUASAFE Range Brochure (Français)",
    category: "Water Safety Labs",
    type: "Brochure",
    language: "French",
    format: "PDF",
    size: "25 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/aquasafe-range-fr.pdf",
    thumbnail: "/brochures/thumbnails/aquasafe-range-fr.png",
    description: "Laboratoires Portables de Sécurité de l'Eau",
  },
  {
    id: "maji-systems-fr",
    title: "MAJI Systems Brochure (Français)",
    category: "Water Quality Meters",
    type: "Brochure",
    language: "French",
    format: "PDF",
    size: "6 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/maji-systems-fr.pdf",
    thumbnail: "/brochures/thumbnails/maji-systems-fr.png",
    description: "Surveillance de la Qualité et du Niveau de l'Eau",
  },
  {
    id: "metalyser-range-fr",
    title: "METALYSER® Range Brochure (Français)",
    category: "Heavy Metals Analysis",
    type: "Brochure",
    language: "French",
    format: "PDF",
    size: "15 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/metalyser-range-fr.pdf",
    thumbnail: "/brochures/thumbnails/metalyser-range-fr.png",
    description: "Analyseurs Portables de Métaux Lourds",
  },
  {
    id: "mobile-labs-fr",
    title: "Laboratoires Mobiles (Français)",
    category: "Mobile Laboratories",
    type: "Brochure",
    language: "French",
    format: "PDF",
    size: "14 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/mobile-laboratories-fr.pdf",
    thumbnail: "/brochures/thumbnails/mobile-laboratories-fr.png",
    description: "Notre Gamme Complète de Laboratoires Mobiles",
  },
  {
    id: "agronomy-catalogue-fr",
    title: "Catalogue Agronomie (Français)",
    category: "Agronomy",
    type: "Catalogue",
    language: "French",
    format: "PDF",
    size: "12 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/agronomy-catalogue-fr.pdf",
    thumbnail: "/brochures/thumbnails/agronomy-catalogue-fr.png",
    description: "Instruments pour les Sciences Agricoles",
  },
  {
    id: "hydromet-fr",
    title: "Hydromet (Français)",
    category: "Hydromet",
    type: "Catalogue",
    language: "French",
    format: "PDF",
    size: "28 MB",
    url: "https://github.com/paulwambaria/wagtech-africa/releases/download/v1.0-assets/hydromet-fr.pdf",
    thumbnail: "/brochures/thumbnails/hydromet-fr.png",
    description: "Systèmes Intégrés pour la Surveillance Météorologique et Climatique",
  },
];

export const partners = [
  {
    id: "wagtech-projects",
    name: "Wagtech Projects UK",
    logo: "/images/partners/wagtech-projects.png",
    description: "Parent company and global headquarters based in the UK — the original brand since 1990.",
    url: "https://www.wagtechprojects.com",
    relationship: "Parent Company",
  },
  {
    id: "trace2o",
    name: "Trace2O",
    logo: "/images/partners/trace2o.png",
    description:
      "Sister company — a global network of research, development, manufacturing, and distribution centres offering complete turnkey analytical and monitoring solutions.",
    url: "https://www.trace2o.com",
    relationship: "Sister Company",
  },
  {
    id: "bruker",
    name: "Bruker",
    logo: "/images/partners/bruker.svg",
    description:
      "Leading manufacturer of scientific instruments — Wagtech Africa is an authorized distributor for Bruker's XRF, XRD, SCD, and MCT analytical instrument ranges.",
    url: "https://www.bruker.com",
    relationship: "Technology Partner",
  },
];

export const trainingServices = [
  {
    id: "installation",
    title: "Installation & Commissioning",
    description:
      "Professional installation and commissioning of all Wagtech equipment by certified engineers on-site across Africa.",
    features: ["On-site installation", "System configuration", "Calibration & verification", "Documentation"],
  },
  {
    id: "operator-training",
    title: "Operator Training",
    description:
      "Hands-on training programs covering equipment operation, maintenance, and troubleshooting for your team.",
    features: [
      "Hands-on practical training",
      "Theory and application sessions",
      "Certification on completion",
      "Training materials provided",
    ],
  },
  {
    id: "technical-support",
    title: "Technical Support",
    description:
      "Ongoing technical assistance from our team of environmental scientists, chemists, and engineers — from initial enquiry to post-sale support.",
    features: ["Phone and email support", "Remote diagnostics", "Application advice", "Troubleshooting guidance"],
  },
  {
    id: "calibration",
    title: "Calibration & Maintenance",
    description:
      "Regular calibration, maintenance, and service to ensure your equipment performs at peak accuracy and reliability.",
    features: [
      "Scheduled calibration services",
      "Preventive maintenance",
      "Reagent supply",
      "Spare parts availability",
    ],
  },
  {
    id: "consultancy",
    title: "Technical Consultancy",
    description:
      "Expert scientific consultancy across environmental sciences, analytical chemistry, agronomy, and civil & public health engineering.",
    features: [
      "Environmental Sciences",
      "Analytical Chemistry",
      "Seed Technology & Agronomy",
      "Civil & Public Health Engineering",
    ],
  },
  {
    id: "after-sales",
    title: "After-Sales Support",
    description:
      "Comprehensive after-sales support including warranty services, spare parts sourcing, and upgrade programs.",
    features: ["Warranty management", "Spare parts supply", "Equipment upgrades", "Service agreements"],
  },
];
